travis:
  secure:
    BINSTAR_TOKEN: QA8+Hmb+PS+8yqaRcg/xZILQfjnrKhhwfJtg6koO1YjmgbI2culCJneVQn9g6Zzx73GRqvcSOs0801dVRT+dwgxQU+n0guvd63PHXLUUYh4Bs4aos8OJRL8ssUffZGjlVMZJmzSMhWlNExoZe5dcEycXYSk5xaRmsdHideGy80zAsEb3hOrp2/nuMJQwaUjN3LMNkatQPtixocDB13uGG6fmkUnfcqUv52izyo/pTDSDcAg2W51Kz2vGhQRXRZPI5qXKfXG/DL1xA4Zmgs3ZNjjWDqsFAFATHA/YK1gNutJ26EG/Oo/CshKw2IfLKBih4GKK3Vbq6mpuDX7r5IWzNOPFAP6BvwypEKKAbUcRAQ9xonjQblX2U0hEWDzD9731j359aJUBOeRulAU/clCz1XJ5i47za0hcdbxZS10tdRte4GnDWKIP3ufsk/02jT5RqOEqc+1WeJP8GaC80H931J4lRuho4km0U1VVQmBftMsG16Gz+QZBJgx4d/GaWKLHtX/zp++hYQF9biHu4p6av11hFXmcMCf/lKs3kH2Z8Sw/3XEkKUWt66U/g/1jTW1/krwQ8sEZq9hipmnuP0Aq0LO3QUzjlFKAfJREY550jIxdwRe4FYpgYsmwqc+HpYQ7V2G5Ls7RJO9I1FSWKBoChBF2btpfb6j1HwP/ud7WK2o=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
